name: Android ROM Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Android ROM
    runs-on: ubuntu-latest

    env:
      JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
      PATH: $JAVA_HOME/bin:$PATH:/usr/bin

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
  uses: actions/setup-java@v3
  with:
    java-version: '8'
    distribution: 'temurin' # You can also use 'zulu', 'adopt', etc., depending on your preference
    cache: 'gradle'
    

    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop openjdk-8-jdk openjdk-8-jre pngcrush schedtool squashfs-tools xsltproc zip zlib1g-dev tar

    - name: Verify `tar` command
      run: |
        which tar
        tar --version

    - name: Initialize repo
      run: |
        mkdir -p ~/kali-touch
        cd ~/kali-touch
        repo init -u https://github.com/Halium/android.git -b halium-7.1

    - name: Sync repo
      run: |
        cd ~/kali-touch
        repo sync

    - name: Clone device tree
      run: |
        cd ~/kali-touch
        git clone https://github.com/LineageOS/android_device_xiaomi_ginkgo -b lineage-17.1 device/xiaomi/ginkgo

    - name: Clone vendor blobs
      run: |
        cd ~/kali-touch
        git clone https://gitlab.com/the-muppets/proprietary_vendor_xiaomi.git -b lineage-17.1 vendor/xiaomi

    - name: Clone kernel source
      run: |
        cd ~/kali-touch
        git clone https://github.com/LineageOS/android_kernel_xiaomi_sm6125.git -b lineage-17.1 kernel/xiaomi/ginkgo

    - name: Setup build environment
      run: |
        cd ~/kali-touch
        source build/envsetup.sh
        lunch lineage_ginkgo-userdebug

    - name: Build bootimage
      run: |
        cd ~/kali-touch
        mka bootimage

    - name: Build systemimage
      run: |
        cd ~/kali-touch
        mka systemimage

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ROM Artifacts
        path: |
          ~/kali-touch/out/target/product/ginkgo/*.img
          
